name: bracket_view_example
description: Example app for bracket_view package.
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bracket_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
